apiVersion: apps/v1
kind: Deployment
metadata:
  name: elearning-blue
  labels:
    app: elearning
    version: blue
spec:
  replicas: 2
  selector:
    matchLabels:
      app: elearning
      version: blue
  template:
    metadata:
      labels:
        app: elearning
        version: blue
    spec:
      containers:
        - name: elearning-container
          image: elearning-website:v1
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: elearning-service
spec:
  selector:
    app: elearning
    version: blue
  ports:
    - port: 80
      targetPort: 80
  type: NodePort


