apiVersion: v1
kind: Service
metadata:
  name: elearning-service
spec:
  selector:
    app: elearning
    version: blue  # This will be updated to green during deployment
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80

