apiVersion: apps/v1
kind: Deployment
metadata:
  name: elearning-green
  labels:
    app: elearning
    version: green
spec:
  replicas: 2
  selector:
    matchLabels:
      app: elearning
      version: green
  template:
    metadata:
      labels:
        app: elearning
        version: green
    spec:
      containers:
        - name: elearning-container
          image: elearning-website:v1
          ports:
            - containerPort: 80


